//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_Monks_Flight_Booking_System.DatabaseInteraction.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBookingInfo
    {
        public int TicketID { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
        public string UnitPrice { get; set; }
        public string TotalAmountCharged { get; set; }
    }
}
